In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
print(arr.shape) # array 형태
print(arr.dtype) # array의 자료형 확인

(4,)
int64


In [4]:
np.arange(10) # 0 ~ 10 array를 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [7]:
arr1.shape

(2, 3)

In [10]:
arr2 = np.array([[10,11,12],[13,14,15]])

In [11]:
arr2.shape

(2, 3)

In [12]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [13]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [14]:
arr1 + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
arr1[0] # 첫번째 row

array([1, 2, 3])

In [17]:
arr1[0][0] 

1

In [18]:
arr1[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1[:, 0:1]

array([[1],
       [4]])